@startuml
skinparam classAttributeIconSize 0

title "Patrón Template Method - CBV Django"

abstract class View {
  + dispatch()
  + get()
  + post()
}

abstract class TemplateView {
  - template_name : String
  + get()
  + get_context_data()
}

abstract class FormView {
  - form_class : Form
  - template_name : String
  - success_url : String

  + get()
  + post()
  + form_valid()
  + form_invalid()
}

class RegView {
  + get()
  + post()
  + form_valid()
  + form_invalid()
}

class LoginView {
  + get()
  + post()
  + form_valid()
  + form_invalid()
}

class LandingView

View <|-- TemplateView
View <|-- FormView

TemplateView <|-- LandingView
FormView <|-- RegView
FormView <|-- LoginView

note top of View
Template Method
dispatch() controla
el flujo de ejecución.
end note

note bottom of RegView
Si el formulario es válido
redirige al login.

Si es inválido
muestra errores.
end note

@enduml